language: node_js
node_js:
  - 14.17.6
before_install:
  - npm install -g codecov
  - npm install -g npm@latest
script:
  - npm run test
  - npm run report-coverage
services:
  - mongodb
before_script:
  - sleep 10
  - mongoimport --db covid --collection casos_1 --type csv --file filtered-s --headerline
  #- mongo covid --eval 'db.createUser({user:"covid",pwd:"covid",roles:[{role:"readWrite",db:"covid"}]});'
