language: node_js
node_js:
  - 14.17.6
services:
  - mongodb
before_script:
  - sleep 30
  #- mongo covid --eval 'db.createUser({user:"covid",pwd:"covid",roles:[{role:"readWrite",db:"covid"}]});'
codecov:
  token: bfe09af6-b8a5-44d6-ab0c-6373a41ce642
