version: '3.7'
services:
  database:
    image: 'mongo'
    container_name: 'mongo'
    environment:
      - "TZ=America/Argentina/Buenos_Aires"
      - MONGO_INITDB_DATABASE=covid
      - MONGO_INITDB_ROOT_USERNAME=covid
      - MONGO_INITDB_ROOT_PASSWORD=covid
    volumes:
      - ./db-data/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./mongo-volume:/data/db
      - ./mongo-import-volume:/data/import
    ports:
      - '27017-27019:27017-27019'
    restart: unless-stopped
  #mongo_seed:
    #image: mongo
    #links:
    #  - database
    #volumes:
    #  - ./mongo-import-volume:/data/import
    #command:
    #  /data/import/import.sh
  covid-app:
    image: 'javiermartingonzalez/covid:latest'
    container_name: 'covid-app'
    environment:
      - "TZ=America/Argentina/Buenos_Aires"
    network_mode: host
    restart: unless-stopped